### ISSUE TITLE
POS Closing Shift Fails 

### ISSUE THREAD

**Issue by arobaz-dev** [BrainWise-DEV/POSNext#19]
Frappe Framework: v15.87.0 (version-15)

ERPNext: v15.85.1 (version-15)

POS Next: v1.1.1 (develop)

App posawesome is not installed
Failed to get method for command posawesome.posawesome.doctype.pos_closing_shift.pos_closing_shift.get_payments_entries with App posawesome is not installed

**Comment by engahmed1190** [comment]
Can you please share more details,  console logs , frappe logs. 
Screen shots or video recording please

**Comment by engahmed1190** [comment]
Thanks @arobaz-dev . This should be fixed now update to version 1.2 then build , migrate and test.

**Comment by arobaz-dev** [comment]
### App Versions
```
{
	"erpnext": "15.86.0",
	"frappe": "15.87.0",
	"pos_next": "1.2.0"
}
```
### Route
```
Form/POS Closing Shift/new-pos-closing-shift-oqlincyvzq
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 50, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 52, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1754, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/pos_next/pos_next/pos_next/doctype/pos_closing_shift/pos_closing_shift.py", line 413, in get_pos_invoices
    submit_printed_invoices(pos_opening_shift, doctype)
  File "apps/pos_next/pos_next/pos_next/doctype/pos_closing_shift/pos_closing_shift.py", line 628, in submit_printed_invoices
    invoices_list = frappe.get_all(
                    ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2047, in get_all
    return get_list(doctype, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 2022, in get_list
    return frappe.model.db_query.DatabaseQuery(doctype).execute(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 212, in execute
    result = self.build_and_run()
             ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/db_query.py", line 255, in build_and_run
    return frappe.db.sql(
           ^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'tabPOS Invoice.posa_pos_opening_shift' in 'WHERE'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"pos_opening_shift": "POSA-OS-25-0000001"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/pos_next.pos_next.doctype.pos_closing_shift.pos_closing_shift.get_pos_invoices",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'tabPOS Invoice.posa_pos_opening_shift' in 'WHERE'\")",
	"exc_type": "OperationalError",
	"_exc_source": "pos_next (app)"
}
```


<img width="1918" height="970" alt="Image" src="https://github.com/user-attachments/assets/97c3eb4a-0c5f-4cb5-8bff-6648a1ea16c5" />

**Comment by engahmed1190** [comment]
Have you migrated the site. This errror means that Custom Fields was not added to tha database

**Comment by arobaz-dev** [comment]
the issue still appears even after rm -rf apps/pos_next

- [x] bench --site site_name reinstall
- [x] bench get-app https://github.com/BrainWise-DEV/pos_next.git --branch develop
- [x] bench --site [your-site-name] install-app pos_next
- [x] bench --site [your-site-name] migrate
- [x] bench build --app pos_next


### App Versions
```
{
	"erpnext": "15.86.0",
	"frappe": "15.87.0",
	"pos_next": "1.2.0"
}
```
### Route
```
Form/POS Closing Shift/new-pos-closing-shift-ouevveommc
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 50, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 52, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1754, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 335, in run_doc_method
    response = doc.run_method(method)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1011, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1371, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1353, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1008, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 32, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/pos_next/pos_next/pos_next/doctype/pos_closing_shift/pos_closing_shift.py", line 252, in get_payment_reconciliation_details
    frappe.db.get_value(
  File "apps/frappe/frappe/database/database.py", line 514, in get_value
    result = self.get_values(
             ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 618, in get_values
    out = self._get_values_from_table(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 891, in _get_values_from_table
    return query.run(as_dict=as_dict, debug=debug, update=update, run=run, pluck=pluck)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/query_builder/utils.py", line 87, in execute_query
    result = frappe.db.sql(query, params, *args, **kwargs)  # nosemgrep
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/database/database.py", line 230, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 563, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 825, in _read_query_result
    result.read()
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 1199, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "env/lib/python3.11/site-packages/pymysql/connections.py", line 775, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.11/site-packages/pymysql/protocol.py", line 219, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.11/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'posa_cash_mode_of_payment' in 'SELECT'")

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"docs": "{\"docstatus\":0,\"doctype\":\"POS Closing Shift\",\"name\":\"new-pos-closing-shift-ouevveommc\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"ramogm@proton.me\",\"period_end_date\":\"2025-11-05 14:05:12\",\"posting_date\":\"2025-11-05\",\"company\":\"Arobaz (Demo)\",\"pos_transactions\":[{\"docstatus\":0,\"doctype\":\"Sales Invoice Reference\",\"name\":\"new-sales-invoice-reference-dafoxksqnf\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"ramogm@proton.me\",\"transaction_currency\":\"TND\",\"parent\":\"new-pos-closing-shift-ouevveommc\",\"parentfield\":\"pos_transactions\",\"parenttype\":\"POS Closing Shift\",\"idx\":1,\"posting_date\":\"2025-11-05\",\"grand_total\":200,\"transaction_amount\":200,\"customer\":\"Palmer Productions Ltd.\",\"sales_invoice\":\"ACC-SINV-2025-00006\"}],\"pos_payments\":[],\"payment_reconciliation\":[{\"docstatus\":0,\"doctype\":\"POS Closing Shift Detail\",\"name\":\"new-pos-closing-shift-detail-mydrwltohq\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"ramogm@proton.me\",\"parent\":\"new-pos-closing-shift-ouevveommc\",\"parentfield\":\"payment_reconciliation\",\"parenttype\":\"POS Closing Shift\",\"idx\":1,\"mode_of_payment\":\"Cash\",\"opening_amount\":0,\"expected_amount\":200}],\"grand_total\":200,\"net_total\":200,\"taxes\":[],\"period_start_date\":\"2025-11-05 13:56:15\",\"pos_profile\":\"Test\",\"user\":\"ramogm@proton.me\",\"pos_opening_shift\":\"POSA-OS-25-0000001\",\"total_quantity\":2}",
		"method": "get_payment_reconciliation_details"
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/run_doc_method",
	"request_id": null
}
```
### Response Data
```
{
	"exception": "pymysql.err.OperationalError: (1054, \"Unknown column 'posa_cash_mode_of_payment' in 'SELECT'\")",
	"exc_type": "OperationalError",
	"_exc_source": "pos_next (app)"
}
```

**Comment by engahmed1190** [comment]
OK. Can you update to the last commit now. I have tried different approache with custom fields.  Update,  Migrate , Clean Cache and Test Again
