### ISSUE TITLE
Allow selecting multiple Serial Numbers for serialized items (auto-set QTY based on selection)

### ISSUE THREAD

**Issue by FadiAlAriqi** [BrainWise-DEV/POSNext#28]
When dealing with an item that is serialized (each unit has its own serial number), after selecting the item and the unit of measure, the system only allows me to select one serial number.

This becomes an issue when I want to sell multiple quantities of the same item, each with a different serial number.

After selecting one serial number (since only one is allowed) and adding the item to the cart, if I increase the QTY (for example from 1 to 4), the system allows it — even though only one serial number was selected.

During checkout, the following validation error appears:

> Validation Error
> For the item <item_code>, the Available qty 1.0 is less than the Required Qty 4.0 in the warehouse <warehouse_name>. Please add sufficient qty in the warehouse.

<img width="1920" height="920" alt="Image" src="https://github.com/user-attachments/assets/28e03525-c75e-409c-91a5-9647222524ec" />

Expected behavior:

- The system should allow selecting multiple serial numbers at once.
- The quantity (QTY) in the cart should automatically match the number of selected serial numbers.
- For example, if I select 3 serial numbers, the item should be added to the cart with QTY = 3.

Actual behavior:
Only one serial number can be selected, yet the quantity can still be changed manually — which causes a validation error during checkout.

Suggestion:
Enable selecting multiple serial numbers for serialized items, and automatically set the item’s quantity based on the number of selected serials.

Question:
Is there a configuration or setting that enables this behavior, or is it currently a limitation/bug?

**Comment by engahmed1190** [comment]
You can allow negative stock from setting and try again

**Comment by engahmed1190** [comment]
Was this resolved by allow negative stock from settings. @FadiAlAriqi . 

This error happens because you have no available stock for the selected.  ERPNEXT have a feature that allows you to sell items that are not available in stock by allowing negative stock. I believe that the validation is correct.  You have one qty if Item and You want to add 3 qty

**Comment by FadiAlAriqi** [comment]
Thank you for your response, but I believe there has been a misunderstanding.

The issue is not related to stock availability. The warehouse has plenty of stock, and every unit has its own Serial Number. The problem occurs because the POS only allows selecting one single Serial Number, as shown in the attached screenshot.

<img width="1920" height="911" alt="Image" src="https://github.com/user-attachments/assets/bdf7ba98-296f-4d6d-8462-c58971ebf6d8" />


So naturally, when I select only one Serial No. but increase the QTY in the cart to 3, the system throws a validation error at checkout — because it doesn’t know which Serial Nos. correspond to the remaining quantities.

This is exactly the core problem:
- The POS should allow selecting multiple Serial Numbers when selling multiple serialized items.
- After selecting the Serial Numbers, the item should be added to the cart with QTY equal to the number of selected serials.

To clarify further:

I did enable “Allow Negative Stock”, and it still does not allow selecting more than one Serial Number.

Again, the issue is not about stock, stock levels are fine — the issue is the UI limitation that restricts Serial Number selection to only one entry.

This feature is essential for serialized inventory workflows, and the current behavior makes it impossible to properly sell multiple serialized items in POS.

Thanks for reconsidering this. I hope this clarifies the issue.

**Comment by engahmed1190** [comment]
Can you test series number after the new update. If you find any issue. Please share screenshot of the browser console and network tab. @FadiAlAriqi

**Comment by FadiAlAriqi** [comment]
I have pulled the latest updates and tested the behavior again.
However, the issue is still not resolved.

What I tested

I followed the exact required steps, including selecting the item and opening the Serial No. dialog:

<img width="1920" height="911" alt="Image" src="https://github.com/user-attachments/assets/ca565417-b126-41e2-b747-504acb8102b0" />

<img width="1920" height="907" alt="Image" src="https://github.com/user-attachments/assets/f37df5ea-d8cc-4fcd-8d03-d25aa3d6265b" />

<img width="1920" height="913" alt="Image" src="https://github.com/user-attachments/assets/95608cac-4c6a-4f5b-9d05-e7476788e1a4" />

Current Behavior

As shown in the screenshot, the POS still does not allow selecting more than one Serial Number:

<img width="1920" height="910" alt="Image" src="https://github.com/user-attachments/assets/1b3c1cc8-7f0b-4acb-b7de-c01e4455e2c3" />

And during checkout, the same validation errors continue to appear:

<img width="1920" height="911" alt="Image" src="https://github.com/user-attachments/assets/fa0b099d-f3fd-408c-b51f-30d61474eacf" />

<img width="1920" height="909" alt="Image" src="https://github.com/user-attachments/assets/b989a72f-0f56-4d3c-afbe-d5afa00b6f10" />

<img width="1920" height="917" alt="Image" src="https://github.com/user-attachments/assets/e479244f-163f-43eb-be81-a6068c1d7116" />

Suggested Solutions

There are two possible approaches that would solve the issue properly:

Solution 1 (recommended):

Allow selecting the quantity in advance in the dialog header, like this:

<img width="1920" height="907" alt="Image" src="https://github.com/user-attachments/assets/eb89c049-4e55-453b-9697-2c4d7ef8c4c6" />

Then, based on that quantity, the system should allow selecting the same number of Serial Numbers in the Serial selection list.

Solution 2:

Alternatively, allow selecting multiple Serial Numbers directly inside the cart, using this dialog:

<img width="1920" height="911" alt="Image" src="https://github.com/user-attachments/assets/56c56837-5138-416a-a562-de69b51d3660" />

Why this is important

Selecting multiple Serial Numbers is essential for POS workflows.
Customers commonly buy several units of the same serialized item, and the POS must allow selecting the exact serial numbers being sold.

Right now, this is not possible, which makes selling serialized items through POS very difficult.

**Comment by FadiAlAriqi** [comment]
I performed the latest test after pulling the most recent commit: "fix: remove autoname field from POS settings configuration".

**Comment by engahmed1190** [comment]
Please join our Telegram group using the link below. I will invite you to our testing platform so you can apply the exact configuration needed to verify this issue:

🔗 [POSNext Telegram](https://t.me/+J2WHnNKCn8ZhOWQ0)

**Comment by FadiAlAriqi** [comment]
I have joined.

**Comment by engahmed1190** [comment]
Closed
